// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwxXVlHlJVuQSA3c7E0evCFH5jcq8AH0A',
    appId: '1:360842637861:web:ef109b2770fdfecedf45cc',
    messagingSenderId: '360842637861',
    projectId: 'renewd-279a8',
    authDomain: 'renewd-279a8.firebaseapp.com',
    storageBucket: 'renewd-279a8.firebasestorage.app',
    measurementId: 'G-8Z5DC0X13B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnfvKn0LimMrAqjQbX_sAUuqOj6hkdBoY',
    appId: '1:360842637861:android:4722ac11e3f62f7adf45cc',
    messagingSenderId: '360842637861',
    projectId: 'renewd-279a8',
    storageBucket: 'renewd-279a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2HaHV_4UB2yHsjMCibv9TbgylbN_jNVg',
    appId: '1:360842637861:ios:5a1203223a85f197df45cc',
    messagingSenderId: '360842637861',
    projectId: 'renewd-279a8',
    storageBucket: 'renewd-279a8.firebasestorage.app',
    androidClientId: '360842637861-sq0kg26gjitchb2kq6fso2g9h6gvdlqb.apps.googleusercontent.com',
    iosClientId: '360842637861-denfn7lu3lnr6844c6e8f99cih2qh9jp.apps.googleusercontent.com',
    iosBundleId: 'com.quartex.renewd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2HaHV_4UB2yHsjMCibv9TbgylbN_jNVg',
    appId: '1:360842637861:ios:08e4c07a8415d9dedf45cc',
    messagingSenderId: '360842637861',
    projectId: 'renewd-279a8',
    storageBucket: 'renewd-279a8.firebasestorage.app',
    androidClientId: '360842637861-sq0kg26gjitchb2kq6fso2g9h6gvdlqb.apps.googleusercontent.com',
    iosClientId: '360842637861-egd8r94lg0bnslsrsi2eitqsk8vvrhmt.apps.googleusercontent.com',
    iosBundleId: 'com.quartex.renewd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwxXVlHlJVuQSA3c7E0evCFH5jcq8AH0A',
    appId: '1:360842637861:web:3cf30fe1f2c1b76fdf45cc',
    messagingSenderId: '360842637861',
    projectId: 'renewd-279a8',
    authDomain: 'renewd-279a8.firebaseapp.com',
    storageBucket: 'renewd-279a8.firebasestorage.app',
    measurementId: 'G-P7HD3DT6HN',
  );
}
